[package]
name = "solana_rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
solana-client = "1.8.0"
serde_json = "1.0.69"
